sonatype-nexus-community/vscode-iq-plugin

ext-src/ComponentInfoPanel.ts, ext-src/VersionInfo.ts, resources/css/styles.css, src/AllVersionsPage.tsx, src/App.tsx, src/ComponentInfoPage.tsx, src/LicensingDisplay.tsx, src/LicensingPage.tsx, src/SecurityItemDisplay.tsx, src/SecurityPage.tsx
Added:
* version list as a selectable data table
* license & security data rendering
* component data, license and security in a single page (cf: CIP)
=> More react improvements

.circleci/config.yml
Quick lil ditty to get CircleCI setup
=> Initial CircleCI

src/SelectedVersionDetails/PolicyPage/PolicyPage.tsx
This is a lil ditty to switch to an Accordion and then get the Chevron Right > Down and back transition working.
=> Policy page updates

README.md, ext-src/packages/LiteComponentContainer.ts, ext-src/packages/PackageDependenciesHelper.ts, ext-src/packages/r/RLiteDependencies.ts, ext-src/packages/r/RPackage.ts, ext-src/packages/r/RUtils.ts, scripts/installed.r
This is a very bare bones R implementation for OSS Index, creating and merging this PR just to make sure it works after the project is packaged/deployed to the Marketplace.
=> BETA R Implementation

ext-src/packages/PackageDependenciesHelper.ts, ext-src/packages/npm/NpmDependencies.ts, ext-src/packages/npm/NpmLiteDependencies.ts, ext-src/packages/npm/NpmScanType.ts, ext-src/packages/npm/NpmUtils.ts
This allows the plugin to work with:
- npm shrinkwrap
- npm package-lock
- yarn lock
This covers the bases with NPM, allowing someone to have fun all across the board!
=> NPM on package lock

ext-src/NexusExplorer.ts
* Adding default policy  sorting
* Closes #74 
* Closes #75 
* Closes #4
=> feat(sorting): default sort policy descending

README.md
little wording improvements from a first-time reader
=> fix typos, rework explanations

ext-src/packages/maven/MavenUtils.ts
1. update mvn dep:tree to support multi-module projects.
2. add dedupe logic to the component list
=> improve support for multi-module maven projects

ext-src/packages/npm/NpmUtils.ts
=> Add command into the error message to help troubleshooting for npm

ext-src/models/IqComponentModel.ts, ext-src/packages/pypi/PyPIDependencies.ts
This is my first time to use Typescript and also editing VS code extension, so please forgive me for any silly mistakes.
By changing the code, it seems pypi scanning is working:
=> Proposing a fix for issue #127 Getting "policyViolations of undefined" on Python package

README.md
=> fix: test release credentials from approved branch

ext-src/packages/npm/NpmDependencies.ts, ext-src/packages/rubygems/RubyGemsUtils.ts, ext-src/packages/rubygems/gemfile.d.ts, ext-src/types/ComponentRequestEntry.ts, package-lock.json, package.json
This allows the extension to get RubyGems deps without having bundler installed!
=> Gemfile parsing like a CHAMP

ext-src/packages/ComponentContainer.ts, ext-src/packages/PackageType.ts, ext-src/packages/golang/GolangCoordinate.ts, ext-src/packages/maven/MavenCoordinate.ts, ext-src/packages/npm/NpmCoordinate.ts, ext-src/packages/pypi/PyPICoordinate.ts, ext-src/packages/rubygems/RubyGemsCoordinate.ts, ext-src/packages/rubygems/RubyGemsDependencies.ts, ext-src/utils/ComponentEntryConversions.ts
Et voila
RubyGems and IQ together again like the best of friends
=> Ruby gems and IQ

ext-src/packages/ComponentContainer.ts, ext-src/packages/LiteComponentContainer.ts, ext-src/packages/poetry/PoetryDependencies.ts, ext-src/packages/poetry/PoetryLiteDependencies.ts, ext-src/packages/poetry/PoetryUtils.ts, package-lock.json
Hey hey hey, another format everyday
=> Poetry - format

ext-src/NexusExplorer.ts, ext-src/extension.ts, ext-src/models/ComponentEntry.ts, ext-src/models/ComponentModel.ts, ext-src/models/ComponentModelOptions.ts, ext-src/models/IqComponentModel.ts, ext-src/models/OssIndexComponentModel.ts, ext-src/utils/Logger.ts, package-lock.json, package.json
The advice for "logging" in VS Code Extensions, seems to be to use an OutputChannel, after a lot of furious googling. There was a library by SAP available to use, but it uses `winston` and in previous experience with `winston`, it's had a lot of security vulnerabilities we couldn't escape. 
Actual creation of the Logger was simple enough, so it's hand rolled atm. This just writes to the `OutputChannel` of `Sonatype IQ Extension`, but that's a huge improvement.
To finish this up, we'd want to make logging some application setting, so people can ultimately get better logs, and default it to likely ERROR, by default. 
Screenshot of it in action:
=> Logging: We can do it

ext-src/NexusExplorer.ts, ext-src/extension.ts
This allows you to switch from OSS Index to IQ and back and forth without having to close VS Code, etc...
Long running annoyance for me.
=> Switch datasources

ext-src/packages/ComponentContainer.ts, ext-src/packages/LiteComponentContainer.ts, ext-src/packages/PackageDependenciesHelper.ts, ext-src/packages/conan/ConanDependencies.ts, ext-src/packages/conan/ConanPackage.ts, ext-src/packages/conan/ConanUtils.ts
Conan, specifically with the lock files from the newer stuff that they are doing.
And yes @allenhsieh I am listening to Powerman 5000 at 8 AM.
=> Conan the format the flamethrower

README.md, ext-src/packages/ComponentContainer.ts, ext-src/packages/LiteComponentContainer.ts, ext-src/packages/gradle/GradleDependencies.ts, ext-src/packages/gradle/GradleUtils.ts
ITS GRADLEEEEEE
* Basic Gradle things from #61 
* Fixes #67 
To test this you'll need to have gradle project locally, and java installed. I do not think you'll need gradle itself (as I execute the gradle wrapper)
=> Gradle - minimal format implementation

ext-src/models/IqComponentModel.ts
=> handling trailing slash for iq report url 

ext-src/models/OssIndexComponentModel.ts, ext-src/services/IqRequestService.ts, ext-src/services/OssIndexRequestService.ts, ext-src/services/RequestHelpers.ts, ext-src/utils/Config.ts, package.json
This will add the OSSI side of reading credentials from the environment variables for #193, supercedes #195
* Added support for reading credentials from env variables using OSSI
* README update
cc @bhamail / @DarthHater / @ButterB0wl
=> Oss index environment variables cherry pick

package-lock.json, src/components/IqServer/AllVersions/SelectedBadge/SelectedBadge.tsx, src/components/IqServer/SelectedVersionDetails/ComponentInfoPage/ComponentInfoPage.css, src/components/IqServer/SelectedVersionDetails/ComponentInfoPage/ComponentInfoPage.tsx, src/components/IqServer/SelectedVersionDetails/SelectedVersionDetails.tsx, webpack.config.js
Simple color change for readability by adding a css file to control the font color
* Add CSS file and set color to black
* Only show popularity if it is available
* Fixes this problem #231
=> Simple color change for readability

.gitignore, ext-src/ComponentInfoPanel.ts, ext-src/NexusExplorer.ts, ext-src/models/IqMultiProjectComponentModel.ts, ext-src/services/IqRequestService.ts
This purely adds additional TRACE logging to help diagnose #241.
=> fix: increase in logging to diagnose #241

ext-src/models/IqMultiProjectComponentModel.ts, ext-src/packages/gradle/GradleUtils.ts, ext-src/services/IqRequestService.ts, ext-src/utils/Logger.ts
given meta data is not displayed in output, add key info in message to have useful info iin output
cc @bhamail / @DarthHater / @madpah
=> improve message to output: meta not displayed

README.md
add instructions on how to get logs from a normal user perspective
cc @bhamail / @DarthHater / @madpah
=> explain how to get logs
