sonatype-nexus-community/vscode-iq-plugin

package-lock.json
package.json

Quick lil dependency update to sidestep #16 , this switches to using the typings dependency for `vscode`, which drags in no dependencies, just types :)
Fixes: #16

Update to use typing instead of old package to fix a DepShield issue

---

ext-src/NexusExplorer.ts
ext-src/models/IqComponentModel.ts
ext-src/models/OssIndexComponentModel.ts
ext-src/services/IqRequestService.ts
ext-src/services/RequestService.ts

A lot of the scans for bigger projects can take quite a while, and we weren't really giving the user any sort of visual feedback as to this.
This PR implements `window.withProgress()` such that things still remain async, but we are able to report progress appropriately.
This hurt my head more than I'd like to admit :)
OSS Index successful scan:
IQ Server successful scan:

Finally, a progress indicator

---

generate-format.sh

While following the steps in: CONTRIBUTING.md, I see the existing `variables.json` file was not using the provided "Format" name. I changed the script to substitute the "Format" name before mustache processing.
Please let me know if I'm totally off base.

Use Format name in template generation script

---

ext-src/packages/PackageDependenciesHelper.ts

Updating getWorkspaceRoot to handle separator differences between platforms. Fixes issue #83.

Updating getWorkspaceRoot

---

ext-src/packages/pypi/PyPiUtils.ts

Basically, on Windows we don't have `cat`, so on the advice of some users, use `type`

Make Python work for Windows

---

ext-src/services/IqRequestService.ts

Fixes a situation where a user has a trailing slash for their IQ Server URL 
Fixes #122

Trim trailing slash on construction of IQRequestService

---

.circleci/config.yml
.gitignore

@Iletee showed me Open VSX earlier today, and it's basically a registry for VS Code compatible extensions. I promised him I would get this done in ten minutes, so here I am!
- Adds build step to publish to Open VSX
- Adds Environment Variable to CircleCI (Done)
- Adds .vsix files to gitignore (noticed they weren't ignored while I fiddled with commands locally)

Add in ability to publish to Open VSX

---

ext-src/NexusExplorer.ts
ext-src/models/IqComponentModel.ts
ext-src/models/OssIndexComponentModel.ts
ext-src/utils/Logger.ts
package-lock.json
package.json

More logs for the log lady.
This uses `log4js` (we use it in `auditjs`, lighter than other loggers), and writes to a logfile in a special extension directory that VS Code creates.
When starting up, based on log level stuff is output in a coarse grain to the `OutputChannel`, more or less so you can follow the bouncing ball (if you want). Fine grained details (objects etc...) are written to a log file. Startup shows you the current log level, as well as where the logs are being written to!
Output in vs code now:
Log Level is now set to ERROR by default, and controlled via a setting in Extension Settings, consistent with everything else. Tested that it works with everything!

File logging

---

ext-src/NexusExplorer.ts
ext-src/models/IqComponentModel.ts
ext-src/models/OssIndexComponentModel.ts
ext-src/services/IqRequestService.ts
ext-src/services/OssIndexRequestService.ts
package-lock.json
package.json

This is basically the start of removing request (very deprecated), in favor of `node-fetch`, the lightest of the libraries that exists.
Works completely for me, dropped `request` and it's types from the package.json, still builds and works, just fine.
Also this starts passing the logger to each service so we can log a lot more!

Kill request

---

ext-src/models/IqComponentModel.ts
package.json

the new order will be much more natural (see #135):
1. Application Id
2. Maximum Evaluation Poll Attempts
3. Server Url
4. Strict SSL
5. Username
6. User Password
(compromise found to have alphabetical ordering that gives sufficient natural order for end user understanding)
I know this change will empty existing configurations to default values for new properties (Server Url and User Password, which replace previous Url and Password), but I really think the new experience is worth that

rename properties to get more natural order #135

---

ext-src/packages/pypi/PyPiUtils.ts

Basically, just use node utils to read requirements.txt, I have no idea why I used `cat` and `type` back when I did it, absolutely goofy when `readFileSync` exists.
This also adds a short circuit to the bit that parses out names and versions, if it can't split on `==` it will just move on to the next line.

Simplify PyPI

---

ext-src/models/IqComponentModel.ts
ext-src/packages/PackageDependencies.ts
ext-src/packages/cargo/CargoDependencies.ts
ext-src/packages/composer/ComposerDependencies.ts
ext-src/packages/golang/GolangDependencies.ts
ext-src/packages/maven/MavenDependencies.ts
ext-src/packages/npm/NpmDependencies.ts
ext-src/packages/poetry/PoetryDependencies.ts
ext-src/packages/pypi/PyPIDependencies.ts
ext-src/packages/rubygems/RubyGemsDependencies.ts
ext-src/packages/templates/Dependencies.mustache
ext-src/services/IqRequestService.ts
ext-src/services/ThirdPartyApiResponse.ts
src/components/Loader/SonatypeLoader.tsx

Quick lil ditty, tighten up some contracts and remove dead code.
Basically, `ConvertToComponentEntry(resultEntry: Array<PackageType>): string;` was moved into a Utils class (we do this portion of things after we exit the package munchers, so it made more sense there, for now), and deleted the implementations on the package munchers. As well made the contract on toComponentEntries tighter for the param it receives).

Simplify Dependencies

---

ext-src/packages/pypi/PyPiUtils.ts

Handle the requirements.txt file containing semicolons in line.  Requirements.txt file auto generated by pipenv can contain these semicolons.
`python-dateutil==2.8.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'`
* Adds a split to the dep line

Handle semicolons in auto-generated requirements.txt files

---

ext-src/models/IqComponentModel.ts
ext-src/services/ApplicationReponse.ts
ext-src/services/IqRequestService.ts
package.json
webpack.config.js

Based on #173 , I wanted to see if it was easy to improve the error logged, as well as just handle everything better.
* Strongly types the app response, so we can do some better stuff with time (what if you find two apps, which one is it?!?!, etc....)
* Moves the logic to parse out the application ID inside the service (it's more appropriate here, consumer shouldn't really care how to parse the json in this case)
* ????
* PROFIT!!!!
* Fixes #173 #87 

Better error from a bad application ID response

---

ext-src/NexusExplorer.ts
ext-src/extension.ts
ext-src/models/IqComponentModel.ts
ext-src/services/IqRequestService.ts
ext-src/services/RequestService.ts
ext-src/utils/Config.ts

Second verse same as the first. Change your Application ID, things refresh. 
* adds constants for all the config for IQ (OSS Index later)
* adds another check for if the config was changed for application ID
* adds a public method to NexusExplorer to update the application ID
* does some rewriting of how setup the config listener, and adds it to the context subscriptions, because it is a disposable!

Refresh IQ stuff when App ID is changed

---

.circleci/config.yml
README.md
package.json

I keep not doing this, and it makes me upset! Let's do this!
* Updates all mentions of `master` to `main`
Once this is merged, we SHOULD be able to just follow the rename directions here: https://github.com/github/renaming

Switch over to main from master

---

ext-src/models/IqComponentModel.ts

Iq trailing slash part 2 electric boogalo

---

ext-src/models/IqComponentModel.ts
ext-src/packages/pypi/PyPiUtils.ts

Basically, this allows someone to have ~= in their requirements.txt and still get results
* Makes the split a regex

Split on == and ~= for requirements.txt

---

ext-src/extension.ts
ext-src/models/IqComponentModel.ts
ext-src/services/IqRequestService.ts
package.json

Quick lil ditty that will pick up a username or token from environment variables:
`NEXUS_IQ_USERNAME`
`NEXUS_IQ_TOKEN`
* Minor tidy and switch to spaces in `extension.ts`
* Ternary that loads either the environment variable or the configuration for username/token
This will require a doc update, and potentially some nice UX stuff at some point, but quick a dirty to allow testing
(If there are changes to user behavior in general, please make sure to
update the docs, as well)

Pick up username or token from environment variables

---

ext-src/utils/exec.ts

Configure any `exec` calls to use the VS Code process's environment variables in addition to any plugin-provided overrides.
Adjusts the `exec` function to incorporate VS Code process's environment variables.
(If there are changes to user behavior in general, please make sure to
update the docs, as well)
* Fixes 191

Merge Process Environment on Exec Calls

---

ext-src/models/IqComponentModel.ts
package.json

Quick bug fix that allows the URL to be populated for showing someone a link to their IQ Server Report
* Sets url to the `.sonatype-config` URL or the existing one.

Ensure url is set if loaded from config

---

ext-src/packages/maven/MavenUtils.ts

Signed-off-by: Paul Horton <phorton@sonatype.com>
Updated parsing of `mvn dependency:tree` output. We were specifically excluding items "omitted for duplicate", but this left comment items that were "omitted for conflict with...".
For the example project in #85 ([cyclonedx-maven-plugin](https://github.com/CycloneDX/cyclonedx-maven-plugin)), the following lines were seen in the output from `mvn dependency:tree`:
```
...
|  |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
|  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.4:compile
|  |     \- (org.codehaus.woodstox:stax2-api:jar:4.2.1:compile - omitted for duplicate)
|  +- com.networknt:json-schema-validator:jar:1.0.58:compile
|  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.12.1:compile - omitted for conflict with …
```

fix: updated parsing logic for `mvn dependency:tree` output to exclude items reported as " ommitted for "

---

README.md
ext-src/models/ComponentEntry.ts
ext-src/packages/gradle/GradleUtils.ts
package-lock.json
package.json

* For projects that contain a `build.gradle`, `./gradlew` or `./gradlew.bat` will now take precedence over system `gradle` when looking to enumerate dependencies for analysis
* Removes duplicate application name in tree view (#227)
* Fixes #226, #227
cc @bhamail / @DarthHater / @maurycupitt

fix: change so that `gradlew` has priority over `gradle`

---

README.md

it helps understanding multi-root Workspaces, but also the (currently implicit) need for a Workspace: if you open just a file and not a folder (synonym for Workspace), you won't get any dependency result

link to VS Code Workspace documentation

---

ext-src/cyclonedx/CycloneDXGenerator.ts

The SBOM creator for VSCode IQ Plugin does not dedupe it's component list, leading to duplicates when IQ parses it, failing validation.
* Adds a function to dedupe the array, based on: https://stackoverflow.com/questions/2218999/how-to-remove-all-duplicates-from-an-array-of-objects

Dedupe components when building SBOM
